### ISSUE TITLE
Export data in CSV file

### ISSUE THREAD

**Issue by christophe33** [christophe33/L1_Projet_Technologique#4]
## TODO
- [x] create a class Point with 2 methods:
- [x] getX(self) -> float
- [x] getY(self) -> float 
- [ ] create a class FileRepo with two méthodes:
- [ ] transformData2CSV
- [ ] export2CSV
